### ISSUE TITLE
关于命令

### ISSUE THREAD

**Issue by pkoiuu** [xiaocheng168/FastAfdPay#2]
作者好像没有写命令

**Comment by xiaocheng168** [comment]
插件没有命令功能目前> 作者好像没有写命令

**Comment by pkoiuu** [comment]
说实话，我在这方面算一个半新手，我现在已经完全配置好了，不解的就是不是说自助充值系统吗，是在游戏内充值然后返还一点奖励，还是在爱发电那边充值，或者是说绑定账户之类的，我是真不懂

> 插件没有命令功能目前> 作者好像没有写命令

**Comment by xiaocheng168** [comment]
目前插件只能做到玩家在爱发电充值后按配置比例给玩家增加点券，你可以提供一些期望功能我未来考虑加入插件中> 说实话，我在这方面算一个半新手，我现在已经完全配置好了，不解的就是不是说自助充值系统吗，是在游戏内充值然后返还一点奖励，还是在爱发电那边充值，或者是说绑定账户之类的，我是真不懂
> 
> 
> 
> > 插件没有命令功能目前> 作者好像没有写命令
> 
> 
> 
>

**Comment by pkoiuu** [comment]
我理解错这一个插件名字的意思,我以为是可以直接在游戏内爱发电的那样子

> 目前插件只能做到玩家在爱发电充值后按配置比例给玩家增加点券，你可以提供一些期望功能我未来考虑加入插件中> 说实话，我在这方面算一个半新手，我现在已经完全配置好了，不解的就是不是说自助充值系统吗，是在游戏内充值然后返还一点奖励，还是在爱发电那边充值，或者是说绑定账户之类的，我是真不懂

**Comment by xiaocheng168** [comment]
> 我理解错这一个插件名字的意思,我以为是可以直接在游戏内爱发电的那样子
> 
> > 目前插件只能做到玩家在爱发电充值后按配置比例给玩家增加点券，你可以提供一些期望功能我未来考虑加入插件中> 说实话，我在这方面算一个半新手，我现在已经完全配置好了，不解的就是不是说自助充值系统吗，是在游戏内充值然后返还一点奖励，还是在爱发电那边充值，或者是说绑定账户之类的，我是真不懂

后续计划增加
1. 购买后自定义礼包
2. 玩家可以快捷在游戏里打开爱发电的链接或者充值二维码
